#!/bin/bash
source /root/.profile

sed "s/^127.0.0.1.*$/127.0.0.1 localhost $(hostname)/" -i /etc/hosts

# Thrift server listens on port 9090 (API) and 9095 (web UI)
/opt/hbase-$HBASE_VERSION/bin/hbase thrift start > /var/log/hbase-thrift.log 2>&1 &

# Thrift server listens on port 9090 (API) and 9095 (web UI)
/opt/hbase-$HBASE_VERSION/bin/hbase thrift start > /var/log/hbase-thrift.log 2>&1 &

exec /opt/hbase-$HBASE_VERSION/bin/hbase master start 2>&1 | tee /var/log/hbase.log
