#!/bin/bash
# Start HBase
#  1) thrift API/Web UI
#  2) hbase master (which runs the local region server)

IP=`ip addr show eth0 | grep 'inet ' | cut -d/ -f1 | awk '{print $2}'`

sed -i "s/@IP@/$IP/g" /opt/hbase/conf/hbase-site.xml

sed -i "s/@IP@/$IP/g" /opt/hbase/conf/zoo.cfg

echo "$IP $(hostname)" >> /etc/hosts

# Thrift server (background)
# Ports: 9090 API and 9095 UI
$HBASE_SERVER thrift start > /opt/hbase/logs/hbase-thrift.log 2>&1 &

# Master server (Foreground) that also starts the region server
# Ports: Master: 60000 API, 60010 UI; 2181 ZK;  Region: 60020 API, 60030 UI
exec $HBASE_SERVER master start 2>&1 | tee /opt/hbase/logs/hbase-master.log
